### Power full Libraries/Packages:
       *  For Data Analysis
           *  Numpy, Pandas, Matplotlib(for visualisation)... etc

# Numpy

#### Numpy : Numerical python

        * Advantages:
            * convenience and speed 
                * Numpy is much faster than the standard python ways to do computations
                * Can write vectorised code on numpy arrays, not on lists
                * which is convenient to read and write
                * It takes Less memory as compared to python lists 
                * Can handle the vast amount of data 

        a. Used for scientific computing and data analysis
        b. Written as ndarray (n-dimensional , homogeneous) or array
            * Commonly integers or floats
        c. Creating Numpy Arrays:
            * 1D, 2D, 3D array
            * Convert lists, tuple to np.arrays

        d. Initialize Array:

            * np.ones(shape,dtype)
            * np.zeros(shape,dtype)
            * np.random.random(shape)
            * np.arange(start,end,step)
            * np.linspace(start,end,length of array)
            * np.full(shape,value)
            * np.tile(array,number of repetitions) or (array,shape)
            * np.eye(value,dtype) - identical matrix
            * np.random.randint(start,end,shape)
            * np.nonzero(array)
            * max,min,median,mode
            * array Transpose
            * np.vstack(array)
            * np.hstack(array
            * argsort,argmin,argmax,np.log10,pi


        e. Inspect the structure and content of array
        
            * np.shape(array)
            * np.dtype()
            * np.ndim()
            * np.itemsize()
            * np.reshape(factors of size of array)


       f.Subset,slice,index through array

            * Single Dimensional array
            * 2D array


In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the rows
* ```axis = 1``` refers to the columns

<img src="axis.jpg" style="width: 600px; height: 400px">



In [4]:
import numpy as np

In [3]:
l = [1,12.2,'str']/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [19]:
# create an 1D_array
a1 = np.array([1,2,3,4,5])
type(a1)
a1.ndim
a1

array([1, 2, 3, 4, 5])

In [14]:
# create an 2D_array
a2 = np.array([[1,0,1],[2,3,2,3]])
a2
print(a2.ndim)
a2


1


array([list([1, 0, 1]), list([2, 3, 2, 3])], dtype=object)

In [18]:
# create an 3D_array
a3 =  np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(a3.ndim)
a3

3


array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [23]:
l = [1,2,3,4]
[i*2 for i in l]

[2, 4, 6, 8]

In [26]:
a1%2

array([1, 0, 1, 0, 1], dtype=int32)

In [27]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [32]:
# np.zeros(shape)   default it returns float
z = np.zeros((3,3),dtype=int)
z.shape
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [39]:
# np.ones
o = np.ones((5,5),dtype=int)
o

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
o*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [41]:
# np.full(shape,value)
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [50]:
# np.random.random(shape)   it returns values in between 0 to 1 
np.random.random((2,3))

array([[0.47643819, 0.96799102, 0.55242945],
       [0.31306753, 0.91968236, 0.60885964]])

In [58]:
# np.random.randint(start,end,no. of values)
np.random.randint(10,108,4)

array([17, 29, 13, 82])

In [73]:
# np.linspace(start,end,length of array, it divides part)
np.linspace(10,109,10)

array([ 10.,  21.,  32.,  43.,  54.,  65.,  76.,  87.,  98., 109.])

In [61]:
#np.arange(start,end,step)
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [64]:
# np.random.randint(start,end,legth/values)
v2 = np.random.randint(10,100,10) # 10 5*2 2*5 10*1 1*10  
v2

array([40, 84, 50, 95, 52, 45, 37, 86, 22, 88])

In [70]:
# np.reshape
v2.reshape(5,2)

array([[40, 84],
       [50, 95],
       [52, 45],
       [37, 86],
       [22, 88]])

In [74]:
[1,2,3,4]*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [76]:
# np.tile(list/tuple,no.of repeatitions)
np.tile([1,2,3,4],3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [92]:
# np.eye identity matrix
print(np.eye(4,7,dtype=int))

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]]


In [89]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [91]:
np.__version__

'1.16.4'

In [102]:
np.nonzero([2.5,5.5,'str',0,0,'str']) # it returns non zero index positionsas an array

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [98]:
import sys
sys.version

'3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]'

In [106]:
j = np.arange(10.9)
j.itemsize

8

In [115]:
t = np.array([[12,34,56,67],[3,5,6,8]])
t

array([[12, 34, 56, 67],
       [ 3,  5,  6,  8]])

In [116]:
t.T

array([[12,  3],
       [34,  5],
       [56,  6],
       [67,  8]])

In [121]:
t.min()

3

In [122]:
t.max()

67

In [124]:
t.mean()

23.875

In [126]:
np.median(t)

10.0

In [127]:
t.argmin()

4

In [128]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [129]:
help(np.argmin)

Help on function argmin in module numpy:

argmin(a, axis=None, out=None)
    Returns the indices of the minimum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmin, argmax
    amin : The minimum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    
    Notes
    -----
    In case of multiple occurrences of the minimum values, the indices
    corresponding to the first occurrence are returned.
    


In [130]:
t

array([[12, 34, 56, 67],
       [ 3,  5,  6,  8]])

In [133]:
np.hstack(t)

array([12, 34, 56, 67,  3,  5,  6,  8])

In [137]:
u = np.array([98,981,2,3,44])
u

array([ 98, 981,   2,   3,  44])

In [138]:
u.argmin()

2

In [139]:
u.argmax()

1

In [143]:
b = np.vstack(u)
b

array([[ 98],
       [981],
       [  2],
       [  3],
       [ 44]])

In [144]:
np.hstack(b)

array([ 98, 981,   2,   3,  44])

In [145]:
np.sqrt(10)

3.1622776601683795

In [146]:
np.sqrt(7)

2.6457513110645907

In [147]:
np.log10(10)

1.0

In [152]:
import math
math.sqrt(45)

6.708203932499369

In [153]:
np.cos(1)

0.5403023058681398

In [154]:
np.cos(90)

-0.4480736161291701

In [155]:
np.sin(10)

-0.5440211108893698

In [156]:
np.sin(90)

0.8939966636005579

In [160]:
np.power(5,1/2)

2.23606797749979

In [159]:
2**(1/2)

1.4142135623730951

In [161]:
# subset

In [168]:
k = np.array([[1,2,3,4],[5,6,7,8],[9,0,8,7]])
k.ndim
type(k)
k.itemsize
k.shape
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 8, 7]])

In [169]:
[start:end ,start :end ]

array([[1, 2, 3, 4]])

In [176]:
k[0]

array([1, 2, 3, 4])

In [172]:
k[2]

array([9, 0, 8, 7])

In [173]:
k[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
array[0]

In [179]:
ap= np.array([[1,2,3],[4,5,6],[7,8,9]])
ap[0]

array([1, 2, 3])

In [183]:
l = np.arange(1000).reshape(10,10,10)
l

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [185]:
l[1]

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [188]:
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 8, 7]])

In [192]:
k[:,0:5]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 8, 7]])

In [193]:
k[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [195]:
k[1:4,2:4]

array([[7, 8],
       [8, 7]])

In [196]:
k[1:3,2:4]


array([[7, 8],
       [8, 7]])

In [197]:
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 8, 7]])

In [209]:
k[1:2,1:2]

array([[6]])

In [ ]:
[start:end ,start:end]

In [199]:
k[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [210]:
k[1:3,1:2] = 10
k

array([[ 1,  2,  3,  4],
       [ 5, 10,  7,  8],
       [ 9, 10,  8,  7]])

In [203]:
import time
t0= time.time()
l1 = [i**2 for i in range(1000000)]
t1= time.time()
print(t1-t0)

0.9237141609191895


In [204]:
import time
t0= time.time()
l1 = np.arange(1000000)**2
t1= time.time()
print(t1-t0)

0.03760099411010742


 # Task 
 using numpy methods
Output:

1 1 1 1 1
1 0 0 0 1
1 0 1 0 1
1 0 0 0 1
1 1 1 1 1

In [212]:
t.shape

(2, 4)